### ISSUE TITLE
Criar rota que lista os horários disponíveis para uma sala

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#1]
# Description
Para se registrar novos horários para uma sala, será necessário verificar antes quais horários já estão ocupados. Nesse sentido, deve criar uma rota: `GET /api/hours/availability`, que recebe como parâmetros um `id de sala` e o `dia da semana`.
Com essas informações, as informações da sala são buscadas, juntamente com seus horários já cadastrados para aquele dia da semana, sendo esses seus horários disponíveis. 
Ao final, é retornada uma lista com os horários disponíveis.

# Additional Context

- **Trabalhar dentro do service de `hours`**

# Tasks

- [x] Implementar lógica no `service`: `listAvailableHoursForRoom`.
- [x] Implementar handler no `controller`
- [x] Implementar rota: `GET /api/hours/availability`.
- [x] Atualizar `CHANGELOG.md`

# Implementation suggestions
