### ISSUE TITLE
Criar rota que cadastra um usuário

### ISSUE THREAD

**Issue by Rafaelraio** [afmireski/OPT120-projeto-final-api#10]
# Description
Um usuário pode criar uma conta no aplicativo, para isso, é necessário uma rota, POST /api/user/create_account, que receberá o email, senha e ra do usuário e criara um usuário com estas credenciais.

# Additional Context
- **Trabalhar no módulo de `users`**

# Tasks

- [x] Implementar lógica no `service`: `createUSER`.
- [x] Implementar handler no `controller`
- [ ] Implementar rota: `POST /api/users/create_account`.
- [ ] Atualizar `CHANGELOG.md`

# Implementation suggestions
