### ISSUE TITLE
Criar rota que loga um usuário

### ISSUE THREAD

**Issue by Rafaelraio** [afmireski/OPT120-projeto-final-api#11]
# Description
Um usuário pode logar em sua conta no aplicativo, para isso, é necessário uma rota, `POST /api/login`, que receberá o RA ou email e a senha do usuário e caso as credenciais do mesmo existam e estejam corretas devolverá um token de acesso para o usuário.

# Additional Context
- **Trabalhar no módulo de `users`**
- `Token`: email, ra, papel.

# Tasks

- [x] Implementar lógica no `service`: `loginUSER`.
- [x] Implementar handler no `controller`
- [x] Implementar rota: `POST /api/login`.
- [x] Implementar middleware de autenticação.
- [x] Implementar middleware de autorização.
- [x] Atualizar `CHANGELOG.md`

# Implementation suggestions
