### ISSUE TITLE
Criar rota que cadastra uma sala

### ISSUE THREAD

**Issue by Rafaelraio** [afmireski/OPT120-projeto-final-api#12]
# Description
Uma sala pode ser criada e, para isso, é necessário uma rota, POST /api/rooms/new, que receberá oque recebe o `nome, informações, e hora de abertura e fechamento de uma sala`. De posse dessas informações, cria uma nova sala. Retorna `void` com código `201`.

# Additional Context
 - **Trabalhar dentro do módulo de `rooms`**

# Tasks

- [ ] Implementar lógica no `service`: `registryNewRoom`.
- [ ] Implementar handler no `controller`
- [ ] Implementar rota: `POST /api/rooms/new``.
- [ ] Atualizar `CHANGELOG.md`

# Implementation suggestions
