### ISSUE TITLE
Criar rota que lista as salas

### ISSUE THREAD

**Issue by Rafaelraio** [afmireski/OPT120-projeto-final-api#13]
# Description
É necessário haver uma forma de listar as salas, nesse sentido, deve-se criar uma rota, `GET /api/rooms`, que listará todas as salas e seus campos. Deve ser possível filtrar as informações por nome e id.

# Additional Context

# Tasks

- [x] Criar middlewares de filtragem e paginação.
- [x]  Implementar lógica no `service`: `listRooms`.
- [x] Implementar handler no `controller`
- [x] Implementar rota: `GET /api/rooms`.
- [x] Atualizar `CHANGELOG.md`

# Implementation suggestions
