### ISSUE TITLE
Criar rota que exclui uma sala

### ISSUE THREAD

**Issue by Rafaelraio** [afmireski/OPT120-projeto-final-api#14]
# Description
Um administrador pode excluir uma sala, para isso, é necessário uma rota, `DELETE /api/api/rooms/:room_id/del`, que receberá o `id da sala` e realizará um `softdelete`.

# Additional Context
- **Trabalhar no módulo de `rooms`**

# Tasks

- [ ] Implementar lógica no `service`: `deleteRoom`.
- [ ] Implementar handler no `controller`
- [ ] Implementar rota: `DELETE /api/rooms/:room_id/del`.
- [ ] Atualizar `CHANGELOG.md`

# Implementation suggestions
