### ISSUE TITLE
Criar uma rota que lista as reservas de um usuário

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#15]
# Description

É interessante para um usuário conseguir listar todas as suas reservas, nesse sentido, deve-se criar uma rota, `GET /api/bookings/users/:user_id`, que recebe o `id do usuário` e devolve todas as suas reservas.

# Additional Context
- **Trabalhar no módulo de `users`**

# Tasks

- [ ] Implementar lógica no `service`: `listUserBookings`.
- [ ] Implementar handler no `controller`
- [ ] Implementar rota: `GET /api/bookings/users/:user_id`.
- [ ] Atualizar `CHANGELOG.md`

# Implementation suggestions
