### ISSUE TITLE
Criar rota que altera informações do usuário

### ISSUE THREAD

**Issue by Rafaelraio** [afmireski/OPT120-projeto-final-api#16]
# Description
Um usuário pode alterar suas informações, para isso, é necessário uma rota, POST /api/user/alter_information, que receberá email ou a senha do usuário e irá alterá-lo.

# Additional Context
- **Trabalhar no módulo de `users`**

# Tasks

- [ ] Implementar lógica no `service`: `alterUSER`.
- [ ] Implementar handler no `controller`
- [ ] Implementar rota: `POST /api/user/alter_information`.
- [ ] Atualizar `CHANGELOG.md`

# Implementation suggestions
