### ISSUE TITLE
Criar rota que permite a administradores cadastrarem novos administradores

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#18]
# Description
Administradores do sistema não podem se cadastrar na plataforma pelos meios normais, devido a seus privilégios. Nesse sentido, é preciso criar uma rota especial de cadastro, `POST /api/users/new-admin`, que servirá para um administrador cadastrar outro administrador.  
A entrada dessa rota será idêntica ao cadastrado normal, porém sem o RA:
```typescript
type Input = {
	email: string;
	nome: string;	
	senha: string;	
}
``` 
Não retorna nada com código `201`.

# Additional Context
## Validações
- O `email` deve ser um e-mail e único
- O nome deve ter entre 3 e 200 caracteres.
- A senha deve ter no mínimo 6 caracteres.
- O usuário deve estar logado e ser um administrador.

# Tasks

- [x] Implementar lógica no `service`: `registerAdmin`.
- [x] Implementar handler no `controller`
- [x] Implementar rota: `POST /api/users/new-admin`.
	- [x] Passar middleware de autenticação
	- [x] Passar middleware de papel
	- [x] Passar middleare de entrada
- [x] Documentar rota na openapi
- [x] Criar um arquivo de seed para pré-criar alguns usuários, como administradores.
- [x] Atualizar `CHANGELOG.md`
