### ISSUE TITLE
Criar rota que cadastra uma lista de horários para uma sala

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#2]
# Description
Uma sala só pode ter novos horários cadastrados em intervalos disponíveis, nesse sentido, é necessário criar uma rota, `POST /api/hours/new`, que recebe o `id de uma sala` e a lista de horários disponíveis geradas em #1.  
De posse dessas informações, cria os novos horários e os vincula a sala. Retorna `void` com código `201`.

# Additional Context
 - **Trabalhar dentro do módulo de `hours`**

# Tasks

- [x] Implementar lógica no `service`: `registryNewHoursForRoom`.
- [x] Implementar handler no `controller`
- [x] Implementar rota: `POST /api/hours/new`.
- [x] Atualizar `CHANGELOG.md`

# Implementation suggestions
