### ISSUE TITLE
Criar rota que busca as informações de um usuário

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#20]
# Description
Todo usuário deve poder visualizar suas informações em seu perfil. Nesse sentido, deve ser criada uma rota, `/api/users/:user_id`, que será responsável por buscar as informações de um usuário.

# Additional Context

# Tasks

- [x] Implementar lógica no `service`: `findUser`.
- [x] Implementar handler no `controller`
- [x] Implementar rota: `GET /api/users/:user_id`.
	- [x] Passar middleware de autenticação
	- [x] Passar middleware de papel
	- [x] Passar middleare de entrada
- [x] Documentar rota na openapi
- [x] Atualizar `CHANGELOG.md`

# Implementation suggestions
