### ISSUE TITLE
Criar rota que permite editar uma sala

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#26]
# Description

É interessante que haja a possibilidade de um Administrador poder as editar as informações de uma sala, mais especificamente: `nome`, `informações`, `hora abertura` e `hora fechamento`.

# Additional Context
- **Nome da rota: `api/rooms/:room_id/edit`**
- Somentre administradores podem acessar essa rota.

## Entrada
```ts
type Input = {
	informations?: Record
	name?: string;
	opening_hour?: Date;
	closing_hour?: Date;
};
```

# Tasks

- [x] Implementar lógica no `service`: `updateRoom`.
- [x] Implementar handler no `controller`
- [x] Implementar rota: `PATCH /api/rooms/:room_id/edit`.
- [x] Documentar rota na `openapi`
- [x] Atualizar `CHANGELOG.md``

# Implementation suggestions
