### ISSUE TITLE
Criar rota que busca as informações de uma sala

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#27]
# Description
Será necessário criar uma rota para buscar em mais detalhes as informações de uma sala: `api/rooms/:room_id`

# Additional Context

# Tasks

# Description
É necessário haver uma forma de listar as salas, nesse sentido, deve-se criar uma rota, `GET /api/rooms`, que listará todas as salas e seus campos. Deve ser possível filtrar as informações por nome e id.

# Additional Context

# Tasks

- [ ]  Implementar lógica no `service`: `findRoomById`.
- [ ] Implementar handler no `controller`
- [ ] Implementar rota: `GET /api/rooms/:room_id`.
- [ ] Documentar rota na openapi
- [ ] Atualizar `CHANGELOG.md`

# Implementation suggestions

# Implementation suggestions
