### ISSUE TITLE
Criar rota que excluí horários de uma sala

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#3]
# Description
É necessário que seja possível excluir os horários de uma sala, nesse sentido, deve-se criar uma rota, `DELETE /api/hours/del`, que recebe o `id da sala` referente aos horários, a lista de ids dos horários, e realiza um `softdelete`.
Ao final do processo, a rota não retorna nada e status `204`.

# Additional Context

# Tasks

- [x] Implementar lógica no `service`: `removeHoursFromRoom`.
- [x] Implementar handler no `controller`
- [x] Implementar rota: `DELETE /api/hours/del`.
- [x] Atualizar `CHANGELOG.md`

# Implementation suggestions
