### ISSUE TITLE
Criar rota que lista os horários disponíveis para reserva num dado período

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#4]
# Description
As reservas de uma sala serão pré-determinadas pelos administradores do sistema. Eles cadastrarão os horários disponíveis para a sala, e depois, os alunos poderão escolher essas reservas.  
Nesse sentido, o administrador tem que saber quais horários, em um dado período, estão disponíveis para serem utilizados em novas reservas.
Para tanto, será criada uma rota: `GET /api/bookings/:sala_id/availability`.

# Additional Context

### Entrada
- `id da sala`
- `lista de dias` onde serão criadas as reservas

# Tasks

- [ ] Implementar lógica no `service`: `listAvailabilityHourForBooking.
- [ ] Implementar handler no `controller`
- [ ] Implementar rota: `GET /api/bookings/:sala_id/availability`.
- [ ] Atualizar `CHANGELOG.md`

# Implementation suggestions

## Lógica
1. Busca todos os horários da sala para o período de entrada.
2. Busca todas as reservas da sala para o período de entrada.
3. Faz um comparativo entre os horários e reservas.
4. Horários que estão atrelados a alguma reserva são marcados como `indisponíveis`.
5. Horários que não estão atrelados a alguma reserva são marcados como `disponíveis`.
6. Devolve o seguinte objeto como resposta:
```ts
type Horario = {
	horarioId: number;
	dia_semana: number;
	data: Date;
	status: "DISPONIVEL" | "INDISPONIVEL"
}

type Output = {
	salaId: number;
	horarios: Horarios[]
}
```

**Comment by afmireski** [comment]
Essa issue não é mais relevante.
