### ISSUE TITLE
Criar rota que cria as intenções de reservas de uma sala para um dado período

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#5]
# Description
As intenções de reservas de uma sala são criadas pelo aluno, ou professor, desde que a sala esteja disponível.  
Nesse sentido, deve-se criar uma rota, `POST /api/bookings/:booking_id/new-intent`, que recebe o `id da reserva`, juntamente com o `id do usuário` que irá reservar a sala.
Ao requisitar a rota, verifica-se se a reserva está mesmo disponível, e então vincula-se o usuário a reserva, marcando-a como aguardando aprovação do moderador.

Importante: Uma intenção de reserva não pode ser criada se aquele horário já possuí uma reserva pendente ou aprovada, a menos que o usuário seja um professor.
Reservas de professor são aprovadas automaticamente, desde que não haja uma reserva aprovada de outro professor antes.

# Additional Context
- **Trabalhar dentro do módulo de `bookings`**

# Tasks

- [ ] Implementar lógica no `service`: `createNewBookingIntent`.
- [ ] Implementar handler no `controller`
- [ ] Implementar rota:  `POST /api/bookings/:booking_id/new-intent`.
- [ ] Atualizar `CHANGELOG.md`

# Implementation suggestions
