### ISSUE TITLE
Criar rota que lista as reservas de uma sala

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#6]
# Description
É necessário haver uma forma de listar as reservas de uma sala, nesse sentido, deve-se criar uma rota, `GET /api/rooms/:room_id/bookings`, que listará todas as reservas de uma sala. Deve ser possível filtrar as informações por data, reservada ou não, usuários.

# Additional Context

# Tasks

- [x] Implementar lógica no `service`: `listBookings`.
- [x] Implementar handler no `controller`
- [x] Implementar rota: `GET /api/rooms/:room_id/bookings`.
- [x] Atualizar `CHANGELOG.md`

# Implementation suggestions
