### ISSUE TITLE
Criar rota que aprova uma reserva

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#7]
# Description
Toda intenção de reserva deve ser aprovada por um moderador (administrador), então, é necessário criar uma rota, `/api/bookings/:booking_id/approve-intent`, que recebe o `id da reserva`, verifica se ela não está aprovada, e a aprova.

# Additional Context
- **Somente administradores podem requisitar essa rota**
- **Trabalhar no módulo de `bookings`**

# Tasks

- [x] Implementar lógica no `service`: `approveBookingIntent`.
- [x] Implementar handler no `controller`
- [x] Implementar rota: `/api/bookings/:booking_id/approve-intent`.
- [x] Atualizar `CHANGELOG.md`

# Implementation suggestions
