### ISSUE TITLE
Criar rota que cancela uma reserva

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#8]
# Description
Um usuário que fez uma reserva, independente dela ter sido aprovada ou não, pode cancelar sua reserva, desde que o momento do início da reserva não tenha passado. Nesse sentido, deve-se criar uma rota, `DELETE /api/bookings/:booking_id/cancel`, que recebe o `id da reserva` e o `id do usuário` que está cancelando. 
Após validar as entradas, desvincula o usuário da reserva e seta `approveded` para `false`, desde que o início da reserva não tenha passado, e o usuário que está cancelando a reserva seja o mesmo que está vinculado a ela.

# Additional Context

- **Trabalhar no módulo de bookings**

# Tasks

- [x] Implementar lógica no `service`: `cancelBooking`.
- [x] Implementar handler no `controller`
- [x] Implementar rota: `POST /api/bookings/:booking_id/cancel`.
- [x] Atualizar `CHANGELOG.md`

# Implementation suggestions
