### ISSUE TITLE
Criar rota que excluí uma reserva

### ISSUE THREAD

**Issue by afmireski** [afmireski/OPT120-projeto-final-api#9]
# Description
Um administrador pode excluir as reservas de uma sala, para isso, é necessário uma rota, `DELETE /api/bookings/:booking_id/del`, que receberá o `id da reserva` e realizará um `softdelete`.

# Additional Context
- **Trabalhar no módulo de `bookings`**

# Tasks

- [ ] Implementar lógica no `service`: `deleteBooking`.
- [x] Implementar handler no `controller`
- [x] Implementar rota: `DELETE /api/bookings/:booking_id/del`.
- [x] Atualizar `CHANGELOG.md`

# Implementation suggestions
